public class partnerSoapSforceCom {
    
    public class LoginResult {
        public String metadataServerUrl;
        public Boolean passwordExpired;
        public Boolean sandbox;
        public String serverUrl;
        public String sessionId;
        public String userId;
        public partnerSoapSforceCom.GetUserInfoResult userInfo;
        private String[] metadataServerUrl_type_info = new String[]{'metadataServerUrl','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] passwordExpired_type_info = new String[]{'passwordExpired','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] sandbox_type_info = new String[]{'sandbox','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] serverUrl_type_info = new String[]{'serverUrl','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] sessionId_type_info = new String[]{'sessionId','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] userId_type_info = new String[]{'userId','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] userInfo_type_info = new String[]{'userInfo','urn:partner.soap.sforce.com',null,'0','1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'metadataServerUrl','passwordExpired','sandbox','serverUrl','sessionId','userId','userInfo'};
                                            }
    
    public class GetUserInfoResult {
        public Boolean accessibilityMode;
        public Boolean chatterExternal;
        public String currencySymbol;
        public Integer orgAttachmentFileSizeLimit;
        public String orgDefaultCurrencyIsoCode;
        public String orgDefaultCurrencyLocale;
        public Boolean orgDisallowHtmlAttachments;
        public Boolean orgHasPersonAccounts;
        public String organizationId;
        public Boolean organizationMultiCurrency;
        public String organizationName;
        public String profileId;
        public String roleId;
        public Integer sessionSecondsValid;
        public String userDefaultCurrencyIsoCode;
        public String userEmail;
        public String userFullName;
        public String userId;
        public String userLanguage;
        public String userLocale;
        public String userName;
        public String userTimeZone;
        public String userType;
        public String userUiSkin;
        private String[] accessibilityMode_type_info = new String[]{'accessibilityMode','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] chatterExternal_type_info = new String[]{'chatterExternal','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] currencySymbol_type_info = new String[]{'currencySymbol','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] orgAttachmentFileSizeLimit_type_info = new String[]{'orgAttachmentFileSizeLimit','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] orgDefaultCurrencyIsoCode_type_info = new String[]{'orgDefaultCurrencyIsoCode','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] orgDefaultCurrencyLocale_type_info = new String[]{'orgDefaultCurrencyLocale','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] orgDisallowHtmlAttachments_type_info = new String[]{'orgDisallowHtmlAttachments','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] orgHasPersonAccounts_type_info = new String[]{'orgHasPersonAccounts','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] organizationId_type_info = new String[]{'organizationId','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] organizationMultiCurrency_type_info = new String[]{'organizationMultiCurrency','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] organizationName_type_info = new String[]{'organizationName','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] profileId_type_info = new String[]{'profileId','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] roleId_type_info = new String[]{'roleId','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] sessionSecondsValid_type_info = new String[]{'sessionSecondsValid','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userDefaultCurrencyIsoCode_type_info = new String[]{'userDefaultCurrencyIsoCode','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] userEmail_type_info = new String[]{'userEmail','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userFullName_type_info = new String[]{'userFullName','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userId_type_info = new String[]{'userId','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userLanguage_type_info = new String[]{'userLanguage','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userLocale_type_info = new String[]{'userLocale','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userName_type_info = new String[]{'userName','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userTimeZone_type_info = new String[]{'userTimeZone','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userType_type_info = new String[]{'userType','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] userUiSkin_type_info = new String[]{'userUiSkin','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'accessibilityMode','chatterExternal','currencySymbol','orgAttachmentFileSizeLimit','orgDefaultCurrencyIsoCode','orgDefaultCurrencyLocale','orgDisallowHtmlAttachments','orgHasPersonAccounts','organizationId','organizationMultiCurrency','organizationName','profileId','roleId','sessionSecondsValid','userDefaultCurrencyIsoCode','userEmail','userFullName','userId','userLanguage','userLocale','userName','userTimeZone','userType','userUiSkin'};
                                                                                                                }
    
    public class SessionHeader_element {
        public String sessionId;
        private String[] sessionId_type_info = new String[]{'sessionId','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'sessionId'};
                    }
    
    public class SaveResult {
        public partnerSoapSforceCom.Error[] errors;
        public String id;
        public Boolean success;
        private String[] errors_type_info = new String[]{'errors','urn:partner.soap.sforce.com',null,'0','-1','false'};
		private String[] id_type_info = new String[]{'id','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] success_type_info = new String[]{'success','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'errors','id','success'};
                            }
    
    public class Error {
        public partnerSoapSforceCom.ExtendedErrorDetails[] extendedErrorDetails;
        public String[] fields;
        public String message;
        public String statusCode;
        private String[] extendedErrorDetails_type_info = new String[]{'extendedErrorDetails','urn:partner.soap.sforce.com',null,'0','-1','true'};
		private String[] fields_type_info = new String[]{'fields','urn:partner.soap.sforce.com',null,'0','-1','true'};
		private String[] message_type_info = new String[]{'message','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] statusCode_type_info = new String[]{'statusCode','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'extendedErrorDetails','fields','message','statusCode'};
                                }
    
    public class ExtendedErrorDetails {
        public String extendedErrorCode;
        private String[] extendedErrorCode_type_info = new String[]{'extendedErrorCode','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'extendedErrorCode'};
                    }
    
    public class DeleteResult {
        public partnerSoapSforceCom.Error[] errors;
        public String id;
        public Boolean success;
        private String[] errors_type_info = new String[]{'errors','urn:partner.soap.sforce.com',null,'0','-1','true'};
		private String[] id_type_info = new String[]{'id','urn:partner.soap.sforce.com',null,'1','1','true'};
		private String[] success_type_info = new String[]{'success','urn:partner.soap.sforce.com',null,'1','1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'errors','id','success'};
                            }
    
    
    
    
    public class create_element {
        public DNPageController.sObject_x[] sObjects;
        private String[] sObjects_type_info = new String[]{'sObjects','urn:partner.soap.sforce.com',null,'0','-1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
		private String[] field_order_type_info = new String[]{'sObjects'};
                    }
    
    
    public class createResponse_element {
        public partnerSoapSforceCom.SaveResult[] result;
        private String[] result_type_info = new String[]{'result','urn:partner.soap.sforce.com',null,'0','-1','false'};
            private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
                private String[] field_order_type_info = new String[]{'result'};
                    }
    
    public class login_element {
        public String username;
        public String password;
        private String[] username_type_info = new String[]{'username','urn:partner.soap.sforce.com',null,'1','1','false'};
        private String[] password_type_info = new String[]{'password','urn:partner.soap.sforce.com',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
        private String[] field_order_type_info = new String[]{'username','password'};
                        }
    
    public class loginResponse_element {
        public partnerSoapSforceCom.LoginResult result;
        private String[] result_type_info = new String[]{'result','urn:partner.soap.sforce.com',null,'1','1','false'};
        private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
        private String[] field_order_type_info = new String[]{'result'};
                    }
    
    public class delete_element {
        public String[] ids;
        private String[] ids_type_info = new String[]{'ids','urn:partner.soap.sforce.com',null,'0','-1','false'};
		private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
        private String[] field_order_type_info = new String[]{'ids'};
                    }
    
    	public class deleteResponse_element {
        public partnerSoapSforceCom.DeleteResult[] result;
        private String[] result_type_info = new String[]{'result','urn:partner.soap.sforce.com',null,'0','-1','false'};
        private String[] apex_schema_type_info = new String[]{'urn:partner.soap.sforce.com','true','false'};
      	private String[] field_order_type_info = new String[]{'result'};
                    }
    
    public class Soap {
        public String endpoint_x = 'https://test.salesforce.com/services/Soap/u/44.0';    
        public partnerSoapSforceCom.SessionHeader_element SessionHeader;    
        private String SessionHeader_hns = 'SessionHeader=urn:partner.soap.sforce.com';
        private String CallOptions_hns = 'CallOptions=urn:partner.soap.sforce.com';
        private String StreamingEnabledHeader_hns = 'StreamingEnabledHeader=urn:partner.soap.sforce.com';
        private String LoginScopeHeader_hns = 'LoginScopeHeader=urn:partner.soap.sforce.com';
        private String UserTerritoryDeleteHeader_hns = 'UserTerritoryDeleteHeader=urn:partner.soap.sforce.com';
        private String DuplicateRuleHeader_hns = 'DuplicateRuleHeader=urn:partner.soap.sforce.com';
        private String[] ns_map_type_info = new String[]{'urn:fault.partner.soap.sforce.com', 'faultPartnerSoapSforceCom', 'urn:sobject.partner.soap.sforce.com', 'sobjectPartnerSoapSforceCom', 'urn:partner.soap.sforce.com', 'partnerSoapSforceCom'};        	
            
            
            public partnerSoapSforceCom.SaveResult[] create(DNPageController.sObject_x[] sObjects) {
                partnerSoapSforceCom.create_element request_x = new partnerSoapSforceCom.create_element();
                request_x.sObjects = sObjects;
                partnerSoapSforceCom.createResponse_element response_x;
                Map<String, partnerSoapSforceCom.createResponse_element> response_map_x = new Map<String, partnerSoapSforceCom.createResponse_element>();
                response_map_x.put('response_x', response_x);
                WebServiceCallout.invoke(
                    this,
                    request_x,
                    response_map_x,
                    new String[]{endpoint_x,
                        '',
                        'urn:partner.soap.sforce.com',
                        'create',
                        'urn:partner.soap.sforce.com',
                        'createResponse',
                        'partnerSoapSforceCom.createResponse_element'}
                );
                response_x = response_map_x.get('response_x');
                return response_x.result;
            }
        
        public partnerSoapSforceCom.LoginResult login(String username,String password) {
            partnerSoapSforceCom.login_element request_x = new partnerSoapSforceCom.login_element();
            request_x.username = username;
            request_x.password = password;
            partnerSoapSforceCom.loginResponse_element response_x;
            Map<String, partnerSoapSforceCom.loginResponse_element> response_map_x = new Map<String, partnerSoapSforceCom.loginResponse_element>();
            response_map_x.put('response_x', response_x);    
            WebServiceCallout.invoke(
                this,
                request_x,
                response_map_x,
                new String[]{endpoint_x,
                    '',
                    'urn:partner.soap.sforce.com',
                    'login',
                    'urn:partner.soap.sforce.com',
                    'loginResponse',
                    'partnerSoapSforceCom.loginResponse_element'}
            );
            response_x = response_map_x.get('response_x');     
            // Schema.DescribeFieldResult dfr = Account.Description.getDescribe();
            
            
            //system.debug('result: '+response_x.result);
            return response_x.result;
        }
        
        public partnerSoapSforceCom.DeleteResult[] delete_x(String[] ids) {
            partnerSoapSforceCom.delete_element request_x = new partnerSoapSforceCom.delete_element();
            request_x.ids = ids;
            partnerSoapSforceCom.deleteResponse_element response_x;
            Map<String, partnerSoapSforceCom.deleteResponse_element> response_map_x = new Map<String, partnerSoapSforceCom.deleteResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
                this,
                request_x,
                response_map_x,
                new String[]{endpoint_x,
                    '',
                    'urn:partner.soap.sforce.com',
                    'delete',
                    'urn:partner.soap.sforce.com',
                    'deleteResponse',
                    'partnerSoapSforceCom.deleteResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.result;
        }      
    }
}